# action.yml
name: 'Run OPA Policies'
author: "Anup Gupta (Smartique)"
description: 'Run OPA Policies on terraform code'
inputs:
  tfplan_json:
    description: 'Terraform plan Json file to evaluate with OPA'
    required: true
    default: "./tfplan.json"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tfplan_json }}
