# action.yml
name: 'Run OPA Policies'
author: "Anup Gupta (Smartique)"
description: 'Run OPA Policies on terraform code'
inputs:
  terraform_code_base_path:
    description: 'Path to Find Terraform Files'
    required: true
    default: "./"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.terraform_code_base_path }}