# action.yml
name: 'Run OPA Policies'
author: "Anup Gupta (Smartique)"
description: 'Run OPA Policies on terraform code'
inputs:
  terraform_code_base_path:
    description: 'Path to Find Terraform Files'
    required: true
    default: "./"
  terraform_version:
    description: 'Terraform Version to use'
    required: true
    default: "1.1.2"
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    TERRAFORM_VERSION: ${{ inputs.terraform_version }}
  args:
    - ${{ inputs.terraform_code_base_path }}
